-- ============================================================
-- 04_raw_tables.sql
-- STEP 4: Create / reconcile all RAW tables
-- Role: SYSADMIN
--
-- RAW is source-aligned: values remain STRING and are not transformed.
-- CREATE OR ALTER avoids destructive DROP + CREATE deployments.
-- ============================================================

USE ROLE SYSADMIN;
USE DATABASE EURORETAIL_DB;
USE SCHEMA RAW;
USE WAREHOUSE EURORETAIL_WH;

CREATE OR ALTER TABLE RAW.DIM_CUSTOMER (
    CUSTOMER_ID   STRING,
    CUSTOMER_NAME STRING,
    SEGMENT       STRING,
    CITY          STRING,
    REGION        STRING,
    COUNTRY       STRING
);

CREATE OR ALTER TABLE RAW.DIM_DATE (
    DATE    STRING,
    YEAR    STRING,
    MONTH   STRING,
    QUARTER STRING
);

CREATE OR ALTER TABLE RAW.DIM_PRODUCT (
    PRODUCT_ID   STRING,
    PRODUCT_NAME STRING,
    CATEGORY     STRING,
    SUB_CATEGORY STRING
);

CREATE OR ALTER TABLE RAW.DIM_STORE (
    STORE_ID   STRING,
    STORE_NAME STRING,
    CITY       STRING,
    REGION     STRING,
    COUNTRY    STRING
);

CREATE OR ALTER TABLE RAW.FACT_SALES (
    ORDER_ID        STRING,
    ORDER_DATE      STRING,
    CUSTOMER_ID     STRING,
    PRODUCT_ID      STRING,
    STORE_ID        STRING,
    QUANTITY        STRING,
    UNIT_PRICE      STRING,
    GROSS_SALES     STRING,
    DISCOUNT_AMOUNT STRING,
    TOTAL_COST      STRING
);

CREATE OR ALTER TABLE RAW.FACT_RETURNS (
    RETURN_ID     STRING,
    ORDER_ID      STRING,
    PRODUCT_ID    STRING,
    RETURN_DATE   STRING,
    RETURN_QTY    STRING,
    REFUND_AMOUNT STRING
);

CREATE OR ALTER TABLE RAW.FACT_SHIPMENTS (
    SHIPMENT_ID     STRING,
    ORDER_ID        STRING,
    SHIP_DATE       STRING,
    SHIP_COST       STRING,
    DELIVERY_STATUS STRING
);
