-- ============================================================
-- 06_verify.sql
-- STEP 6: RAW load verification and operational checks
-- Role: SYSADMIN
-- ============================================================

USE ROLE SYSADMIN;
USE DATABASE EURORETAIL_DB;
USE SCHEMA RAW;
USE WAREHOUSE EURORETAIL_WH;

-- 1. Row counts across all source-aligned tables.
SELECT 'DIM_CUSTOMER' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM RAW.DIM_CUSTOMER
UNION ALL SELECT 'DIM_DATE', COUNT(*) FROM RAW.DIM_DATE
UNION ALL SELECT 'DIM_PRODUCT', COUNT(*) FROM RAW.DIM_PRODUCT
UNION ALL SELECT 'DIM_STORE', COUNT(*) FROM RAW.DIM_STORE
UNION ALL SELECT 'FACT_SALES', COUNT(*) FROM RAW.FACT_SALES
UNION ALL SELECT 'FACT_RETURNS', COUNT(*) FROM RAW.FACT_RETURNS
UNION ALL SELECT 'FACT_SHIPMENTS', COUNT(*) FROM RAW.FACT_SHIPMENTS
ORDER BY TABLE_NAME;

-- 2. Load history: failed COPY operations must be investigated before
--    promoting data into STAGING.
SELECT
    TABLE_NAME,
    FILE_NAME,
    LAST_LOAD_TIME,
    STATUS,
    ROW_COUNT,
    ERROR_COUNT,
    FIRST_ERROR_MESSAGE
FROM INFORMATION_SCHEMA.LOAD_HISTORY
WHERE SCHEMA_NAME = 'RAW'
  AND LAST_LOAD_TIME >= DATEADD(DAY, -14, CURRENT_TIMESTAMP())
ORDER BY LAST_LOAD_TIME DESC;

-- 3. Critical source-field null checks.
SELECT
    'FACT_SALES.ORDER_ID' AS CHECK_NAME,
    COUNT_IF(NULLIF(TRIM(ORDER_ID), '') IS NULL) AS FAILED_ROWS
FROM RAW.FACT_SALES
UNION ALL
SELECT
    'FACT_SALES.ORDER_DATE',
    COUNT_IF(NULLIF(TRIM(ORDER_DATE), '') IS NULL)
FROM RAW.FACT_SALES
UNION ALL
SELECT
    'FACT_SALES.CUSTOMER_ID',
    COUNT_IF(NULLIF(TRIM(CUSTOMER_ID), '') IS NULL)
FROM RAW.FACT_SALES;

-- 4. Preview only after load verification.
SELECT * FROM RAW.DIM_CUSTOMER LIMIT 5;
SELECT * FROM RAW.DIM_PRODUCT LIMIT 5;
SELECT * FROM RAW.FACT_SALES LIMIT 5;
