-- ============================================================
--  06_verify.sql
--  STEP 6: Verify Load Quality
--  Run as: ACCOUNTADMIN
-- ============================================================

USE ROLE ACCOUNTADMIN;
USE DATABASE EURORETAIL_DB;
USE SCHEMA RAW;
USE WAREHOUSE EURORETAIL_WH;

-- Row count across all 7 tables
SELECT 'DIM_CUSTOMER'   AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM RAW.DIM_CUSTOMER   UNION ALL
SELECT 'DIM_DATE'       AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM RAW.DIM_DATE       UNION ALL
SELECT 'DIM_PRODUCT'    AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM RAW.DIM_PRODUCT    UNION ALL
SELECT 'DIM_STORE'      AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM RAW.DIM_STORE      UNION ALL
SELECT 'FACT_SALES'     AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM RAW.FACT_SALES     UNION ALL
SELECT 'FACT_RETURNS'   AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM RAW.FACT_RETURNS   UNION ALL
SELECT 'FACT_SHIPMENTS' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM RAW.FACT_SHIPMENTS
ORDER BY TABLE_NAME;

-- Sample preview
SELECT * FROM RAW.DIM_CUSTOMER   LIMIT 5;
SELECT * FROM RAW.DIM_PRODUCT    LIMIT 5;
SELECT * FROM RAW.FACT_SALES     LIMIT 5;

-- Load history — check for errors or skipped rows
SELECT
    TABLE_NAME,
    FILE_NAME,
    LAST_LOAD_TIME,
    STATUS,
    ROW_COUNT,
    ERROR_COUNT,
    FIRST_ERROR_MESSAGE
FROM INFORMATION_SCHEMA.LOAD_HISTORY
WHERE SCHEMA_NAME = 'RAW'
ORDER BY LAST_LOAD_TIME DESC;

-- NULL check on critical column
SELECT COUNT(*) AS NULL_ORDER_DATES
FROM RAW.FACT_SALES
WHERE ORDER_DATE IS NULL;
