-- ============================================================
-- 01_reporting_views.sql
-- Layer 3: business-facing reporting views
-- Role: SYSADMIN
--
-- These views are intentionally narrow and BI-friendly. They keep
-- business logic in Snowflake while leaving presentation to Power BI.
-- ============================================================

USE ROLE SYSADMIN;
USE DATABASE EURORETAIL_DB;
USE SCHEMA REPORTING;
USE WAREHOUSE EURORETAIL_WH;

CREATE OR ALTER VIEW REPORTING.DAILY_SALES AS
SELECT
    ORDER_DATE,
    COUNT(DISTINCT ORDER_ID) AS ORDER_COUNT,
    SUM(QUANTITY) AS UNITS_SOLD,
    ROUND(SUM(GROSS_SALES), 2) AS GROSS_REVENUE,
    ROUND(SUM(DISCOUNT_AMOUNT), 2) AS DISCOUNT_AMOUNT,
    ROUND(SUM(NET_SALES), 2) AS NET_REVENUE,
    ROUND(SUM(TOTAL_COST), 2) AS TOTAL_COST,
    ROUND(SUM(NET_SALES) - SUM(TOTAL_COST), 2) AS GROSS_MARGIN
FROM STAGING.FACT_SALES
GROUP BY ORDER_DATE;

CREATE OR ALTER VIEW REPORTING.CUSTOMER_SALES AS
SELECT
    c.CUSTOMER_ID,
    c.CUSTOMER_NAME,
    c.SEGMENT,
    c.REGION,
    c.COUNTRY,
    COUNT(DISTINCT s.ORDER_ID) AS ORDER_COUNT,
    SUM(s.QUANTITY) AS UNITS_SOLD,
    ROUND(SUM(s.NET_SALES), 2) AS NET_REVENUE,
    ROUND(SUM(s.TOTAL_COST), 2) AS TOTAL_COST,
    ROUND(SUM(s.NET_SALES) - SUM(s.TOTAL_COST), 2) AS GROSS_MARGIN
FROM STAGING.FACT_SALES s
JOIN STAGING.DIM_CUSTOMER c
    ON s.CUSTOMER_ID = c.CUSTOMER_ID
GROUP BY
    c.CUSTOMER_ID,
    c.CUSTOMER_NAME,
    c.SEGMENT,
    c.REGION,
    c.COUNTRY;

CREATE OR ALTER VIEW REPORTING.PRODUCT_PERFORMANCE AS
SELECT
    p.PRODUCT_ID,
    p.PRODUCT_NAME,
    p.CATEGORY,
    p.SUB_CATEGORY,
    COUNT(DISTINCT s.ORDER_ID) AS ORDER_COUNT,
    SUM(s.QUANTITY) AS UNITS_SOLD,
    ROUND(SUM(s.NET_SALES), 2) AS NET_REVENUE,
    ROUND(SUM(s.TOTAL_COST), 2) AS TOTAL_COST,
    ROUND(SUM(s.NET_SALES) - SUM(s.TOTAL_COST), 2) AS GROSS_MARGIN
FROM STAGING.FACT_SALES s
JOIN STAGING.DIM_PRODUCT p
    ON s.PRODUCT_ID = p.PRODUCT_ID
GROUP BY
    p.PRODUCT_ID,
    p.PRODUCT_NAME,
    p.CATEGORY,
    p.SUB_CATEGORY;

CREATE OR ALTER VIEW REPORTING.RETURNS_SUMMARY AS
SELECT
    r.PRODUCT_ID,
    COUNT(DISTINCT r.RETURN_ID) AS RETURN_COUNT,
    SUM(r.RETURN_QTY) AS RETURN_UNITS,
    ROUND(SUM(r.REFUND_AMOUNT), 2) AS REFUND_AMOUNT
FROM STAGING.FACT_RETURNS r
GROUP BY r.PRODUCT_ID;

CREATE OR ALTER VIEW REPORTING.DELIVERY_PERFORMANCE AS
SELECT
    DELIVERY_STATUS,
    COUNT(DISTINCT SHIPMENT_ID) AS SHIPMENT_COUNT,
    ROUND(AVG(SHIP_COST), 2) AS AVG_SHIP_COST,
    ROUND(SUM(SHIP_COST), 2) AS TOTAL_SHIP_COST
FROM STAGING.FACT_SHIPMENTS
GROUP BY DELIVERY_STATUS;

-- Executive KPI view for a BI landing page.
CREATE OR ALTER VIEW REPORTING.EXECUTIVE_KPIS AS
SELECT
    (SELECT COUNT(DISTINCT ORDER_ID) FROM STAGING.FACT_SALES) AS TOTAL_ORDERS,
    (SELECT SUM(QUANTITY) FROM STAGING.FACT_SALES) AS TOTAL_UNITS,
    (SELECT ROUND(SUM(NET_SALES), 2) FROM STAGING.FACT_SALES) AS TOTAL_NET_REVENUE,
    (SELECT ROUND(SUM(NET_SALES) - SUM(TOTAL_COST), 2) FROM STAGING.FACT_SALES) AS TOTAL_GROSS_MARGIN,
    (SELECT COUNT(DISTINCT RETURN_ID) FROM STAGING.FACT_RETURNS) AS TOTAL_RETURNS,
    (SELECT COUNT(DISTINCT SHIPMENT_ID) FROM STAGING.FACT_SHIPMENTS) AS TOTAL_SHIPMENTS;
