-- ============================================================
-- 01_staging_views.sql
-- Layer 2: typed, normalized staging views
-- Role: SYSADMIN
--
-- RAW remains unchanged. TRY_* conversions make malformed source
-- values visible as NULL instead of aborting downstream queries.
-- ============================================================

USE ROLE SYSADMIN;
USE DATABASE EURORETAIL_DB;
USE SCHEMA STAGING;
USE WAREHOUSE EURORETAIL_WH;

CREATE OR ALTER VIEW STAGING.DIM_CUSTOMER AS
SELECT
    NULLIF(TRIM(CUSTOMER_ID), '') AS CUSTOMER_ID,
    NULLIF(TRIM(CUSTOMER_NAME), '') AS CUSTOMER_NAME,
    NULLIF(TRIM(SEGMENT), '') AS SEGMENT,
    NULLIF(TRIM(CITY), '') AS CITY,
    NULLIF(TRIM(REGION), '') AS REGION,
    NULLIF(TRIM(COUNTRY), '') AS COUNTRY,
    SHA2(NULLIF(TRIM(CUSTOMER_ID), ''), 256) AS CUSTOMER_KEY
FROM RAW.DIM_CUSTOMER;

CREATE OR ALTER VIEW STAGING.DIM_DATE AS
SELECT
    TRY_TO_DATE(NULLIF(TRIM(DATE), '')) AS DATE_VALUE,
    TRY_TO_NUMBER(NULLIF(TRIM(YEAR), '')) AS YEAR,
    NULLIF(TRIM(MONTH), '') AS MONTH,
    NULLIF(TRIM(QUARTER), '') AS QUARTER,
    TRY_TO_NUMBER(TO_CHAR(TRY_TO_DATE(NULLIF(TRIM(DATE), '')), 'YYYYMMDD')) AS DATE_KEY
FROM RAW.DIM_DATE;

CREATE OR ALTER VIEW STAGING.DIM_PRODUCT AS
SELECT
    NULLIF(TRIM(PRODUCT_ID), '') AS PRODUCT_ID,
    NULLIF(TRIM(PRODUCT_NAME), '') AS PRODUCT_NAME,
    NULLIF(TRIM(CATEGORY), '') AS CATEGORY,
    NULLIF(TRIM(SUB_CATEGORY), '') AS SUB_CATEGORY,
    SHA2(NULLIF(TRIM(PRODUCT_ID), ''), 256) AS PRODUCT_KEY
FROM RAW.DIM_PRODUCT;

CREATE OR ALTER VIEW STAGING.DIM_STORE AS
SELECT
    NULLIF(TRIM(STORE_ID), '') AS STORE_ID,
    NULLIF(TRIM(STORE_NAME), '') AS STORE_NAME,
    NULLIF(TRIM(CITY), '') AS CITY,
    NULLIF(TRIM(REGION), '') AS REGION,
    NULLIF(TRIM(COUNTRY), '') AS COUNTRY,
    SHA2(NULLIF(TRIM(STORE_ID), ''), 256) AS STORE_KEY
FROM RAW.DIM_STORE;

CREATE OR ALTER VIEW STAGING.FACT_SALES AS
SELECT
    NULLIF(TRIM(ORDER_ID), '') AS ORDER_ID,
    TRY_TO_DATE(NULLIF(TRIM(ORDER_DATE), '')) AS ORDER_DATE,
    NULLIF(TRIM(CUSTOMER_ID), '') AS CUSTOMER_ID,
    NULLIF(TRIM(PRODUCT_ID), '') AS PRODUCT_ID,
    NULLIF(TRIM(STORE_ID), '') AS STORE_ID,
    TRY_TO_NUMBER(NULLIF(TRIM(QUANTITY), '')) AS QUANTITY,
    TRY_TO_DECIMAL(NULLIF(TRIM(UNIT_PRICE), ''), 18, 2) AS UNIT_PRICE,
    TRY_TO_DECIMAL(NULLIF(TRIM(GROSS_SALES), ''), 18, 2) AS GROSS_SALES,
    TRY_TO_DECIMAL(NULLIF(TRIM(DISCOUNT_AMOUNT), ''), 18, 2) AS DISCOUNT_AMOUNT,
    TRY_TO_DECIMAL(NULLIF(TRIM(TOTAL_COST), ''), 18, 2) AS TOTAL_COST,
    TRY_TO_DECIMAL(NULLIF(TRIM(GROSS_SALES), ''), 18, 2)
        - COALESCE(TRY_TO_DECIMAL(NULLIF(TRIM(DISCOUNT_AMOUNT), ''), 18, 2), 0) AS NET_SALES,
    SHA2(NULLIF(TRIM(ORDER_ID), ''), 256) AS ORDER_KEY
FROM RAW.FACT_SALES;

CREATE OR ALTER VIEW STAGING.FACT_RETURNS AS
SELECT
    NULLIF(TRIM(RETURN_ID), '') AS RETURN_ID,
    NULLIF(TRIM(ORDER_ID), '') AS ORDER_ID,
    NULLIF(TRIM(PRODUCT_ID), '') AS PRODUCT_ID,
    TRY_TO_DATE(NULLIF(TRIM(RETURN_DATE), '')) AS RETURN_DATE,
    TRY_TO_NUMBER(NULLIF(TRIM(RETURN_QTY), '')) AS RETURN_QTY,
    TRY_TO_DECIMAL(NULLIF(TRIM(REFUND_AMOUNT), ''), 18, 2) AS REFUND_AMOUNT
FROM RAW.FACT_RETURNS;

CREATE OR ALTER VIEW STAGING.FACT_SHIPMENTS AS
SELECT
    NULLIF(TRIM(SHIPMENT_ID), '') AS SHIPMENT_ID,
    NULLIF(TRIM(ORDER_ID), '') AS ORDER_ID,
    TRY_TO_DATE(NULLIF(TRIM(SHIP_DATE), '')) AS SHIP_DATE,
    TRY_TO_DECIMAL(NULLIF(TRIM(SHIP_COST), ''), 18, 2) AS SHIP_COST,
    NULLIF(TRIM(DELIVERY_STATUS), '') AS DELIVERY_STATUS
FROM RAW.FACT_SHIPMENTS;
