-- ============================================================
-- 02_data_quality_checks.sql
-- Layer 2: data quality assertions
-- Role: SYSADMIN
--
-- Expected result: every CHECK_STATUS should be PASS.
-- ============================================================

USE ROLE SYSADMIN;
USE DATABASE EURORETAIL_DB;
USE SCHEMA STAGING;
USE WAREHOUSE EURORETAIL_WH;

WITH checks AS (
    SELECT
        'DIM_CUSTOMER_CUSTOMER_ID' AS CHECK_NAME,
        IFF(COUNT_IF(CUSTOMER_ID IS NULL) = 0, 'PASS', 'FAIL') AS CHECK_STATUS,
        COUNT_IF(CUSTOMER_ID IS NULL) AS FAILED_ROWS
    FROM STAGING.DIM_CUSTOMER

    UNION ALL
    SELECT
        'DIM_PRODUCT_PRODUCT_ID',
        IFF(COUNT_IF(PRODUCT_ID IS NULL) = 0, 'PASS', 'FAIL'),
        COUNT_IF(PRODUCT_ID IS NULL)
    FROM STAGING.DIM_PRODUCT

    UNION ALL
    SELECT
        'DIM_STORE_STORE_ID',
        IFF(COUNT_IF(STORE_ID IS NULL) = 0, 'PASS', 'FAIL'),
        COUNT_IF(STORE_ID IS NULL)
    FROM STAGING.DIM_STORE

    UNION ALL
    SELECT
        'FACT_SALES_ORDER_ID',
        IFF(COUNT_IF(ORDER_ID IS NULL) = 0, 'PASS', 'FAIL'),
        COUNT_IF(ORDER_ID IS NULL)
    FROM STAGING.FACT_SALES

    UNION ALL
    SELECT
        'FACT_SALES_ORDER_DATE',
        IFF(COUNT_IF(ORDER_DATE IS NULL) = 0, 'PASS', 'FAIL'),
        COUNT_IF(ORDER_DATE IS NULL)
    FROM STAGING.FACT_SALES

    UNION ALL
    SELECT
        'FACT_SALES_NUMERIC_FIELDS',
        IFF(COUNT_IF(QUANTITY IS NULL OR UNIT_PRICE IS NULL OR GROSS_SALES IS NULL) = 0, 'PASS', 'FAIL'),
        COUNT_IF(QUANTITY IS NULL OR UNIT_PRICE IS NULL OR GROSS_SALES IS NULL)
    FROM STAGING.FACT_SALES

    UNION ALL
    SELECT
        'FACT_SALES_CUSTOMER_REFERENCES',
        IFF(COUNT_IF(s.CUSTOMER_ID IS NOT NULL AND c.CUSTOMER_ID IS NULL) = 0, 'PASS', 'FAIL'),
        COUNT_IF(s.CUSTOMER_ID IS NOT NULL AND c.CUSTOMER_ID IS NULL)
    FROM STAGING.FACT_SALES s
    LEFT JOIN STAGING.DIM_CUSTOMER c ON s.CUSTOMER_ID = c.CUSTOMER_ID

    UNION ALL
    SELECT
        'FACT_SALES_PRODUCT_REFERENCES',
        IFF(COUNT_IF(s.PRODUCT_ID IS NOT NULL AND p.PRODUCT_ID IS NULL) = 0, 'PASS', 'FAIL'),
        COUNT_IF(s.PRODUCT_ID IS NOT NULL AND p.PRODUCT_ID IS NULL)
    FROM STAGING.FACT_SALES s
    LEFT JOIN STAGING.DIM_PRODUCT p ON s.PRODUCT_ID = p.PRODUCT_ID
)
SELECT CHECK_NAME, CHECK_STATUS, FAILED_ROWS
FROM checks
ORDER BY CHECK_STATUS DESC, CHECK_NAME;
